<html>
<body>
<ul>
    <li>${smallArray[0]}</li>
	<li>${smallArray[1]}</li>
	<li>${smallArray[2]}</li>
	<li>${smallArray[3]}</li>
	<li>${smallArray[4]}</li>
	<li>${smallArray[5]}</li>
	<li>${smallArray[6][0]}</li>
	<li>${smallArray[7].theOtherestSquirrel}</li>
</ul>
</body>
</html>
